apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-backend
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  flask-secret-key: {{ randAlphaNum 32 | b64enc | quote }}
