apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: redbuild-app

# --- GLOBAL BUILD CONFIG ---
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: redbuild-frontend
      context: frontend
      docker: { dockerfile: Dockerfile }
    - image: redbuild-backend
      context: backend
      docker: { dockerfile: Dockerfile }
    - image: win-c-compiler-worker
      context: backend
      docker: { dockerfile: generators/compiler/Dockerfile }

# --- GLOBAL PORT FORWARD ---
portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: backend-api-service
    port: 5000
    localPort: 5001

# --- PROFILES ---
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
      artifacts:
        - image: redbuild-frontend
          context: frontend
          docker: { dockerfile: Dockerfile.dev }
          sync:
            infer: ['**/*']
        - image: redbuild-backend
          context: backend
          docker: { dockerfile: Dockerfile.dev }
          sync:
            infer: ['**/*']
        - image: win-c-compiler-worker
          context: backend
          docker: { dockerfile: generators/compiler/Dockerfile }
    deploy:
      helm:
        releases:
          - name: redbuild-app
            chartPath: ./k8s/helm-chart
            setValueTemplates:
              frontend.image: '{{.IMAGE_FULLY_QUALIFIED_redbuild_frontend}}'
              backend.image: '{{.IMAGE_FULLY_QUALIFIED_redbuild_backend}}'
              backend.workerImage: '{{.IMAGE_FULLY_QUALIFIED_win_c_compiler_worker}}'

  # --- MONITORING PROFILE ---
  - name: monitoring
    deploy:
      helm:
        releases:
          - name: prometheus
            repo: https://prometheus-community.github.io/helm-charts
            remoteChart: kube-prometheus-stack
            namespace: monitoring
            createNamespace: true
            wait: true
            valuesFiles:
              - k8s/helm-chart/prometheus-values.yaml

          - name: loki
            repo: https://grafana.github.io/helm-charts
            remoteChart: loki-stack
            namespace: monitoring
            createNamespace: true
            wait: true
            valuesFiles:
              - k8s/helm-chart/loki-values.yaml

          - name: alloy
            repo: https://grafana.github.io/helm-charts
            remoteChart: alloy
            namespace: monitoring
            createNamespace: true
            wait: true
            valuesFiles:
              - k8s/helm-chart/alloy-values.yaml

  # --- PROD PROFILES ---
  - name: prod
    build:
      local:
        push: true

  - name: local-prod
    build:
      local:
        push: false
