apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: redbuild-app
build:
  local:
    push: false
  artifacts:
    - image: redbuild-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*'
            dest: /usr/share/nginx/html
    - image: redbuild-backend
      context: backend
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'app/**/*.py'
            dest: /app
          - src: 'requirements.txt'
            dest: /app
    - image: win-c-compiler-worker
      context: backend
      docker:
        dockerfile: generators/compiler/Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/api-rbac.yaml
      - k8s/shared-volume-pvc.yaml
      - k8s/frontend-*.yaml
      - k8s/backend-api-*.yaml

portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: backend-api-service
    port: 5000
    localPort: 5001
