apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: redbuild-app
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.TAG}}"
  local:
    push: false
  artifacts:
    - image: redbuild-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile.dev
    - image: redbuild-backend
      context: backend
      docker:
        dockerfile: Dockerfile.dev
    - image: win-c-compiler-worker
      context: backend
      docker:
        dockerfile: generators/compiler/Dockerfile

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: frontend-service
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: backend-api-service
    port: 5000
    localPort: 5001

