apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: job-manager-sa
      containers:
      - name: api
        image: redbuild-backend
        command: ["python", "run.py"]
        env: []
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: uploads-storage
          mountPath: /tmp/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: shared-uploads-pvc
