grafana:
  enabled: true
  
  additionalDataSources:
    - name: "Loki"
      type: "loki"
      access: "proxy"
      uid: "loki"
      url: "http://loki-gateway.monitoring.svc.cluster.local" 
      jsonData:
        derivedFields:
          - datasourceUid: 'prometheus'
            matcherRegex: 'cluster="([^"]+)"'
            name: 'cluster'

    - name: "Tempo"
      type: "tempo"
      access: "proxy"
      uid: "tempo"
      url: "http://tempo.monitoring.svc.cluster.local:3200"
      jsonData:
        httpMethod: "GET"
        lokiSearch:
          datasourceUid: "loki"
        nodeGraph:
          enabled: true
        serviceMap:
          datasourceUid: "prometheus"
        tracesToLogsV2:
          datasourceUid: "loki"
          spanAttributes: [ "service.name", "task_id" ]
        tracesToMetrics:
          datasourceUid: "prometheus"
          spanAttributes: [ "service.name" ]

kubelet:
  enabled: true
  serviceMonitor:
    https: true
    insecure_skip_verify: true

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    retention: 2d
    retentionSize: 2GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi
