apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redbuild-frontend
  template:
    metadata:
      labels:
        app: redbuild-frontend
    spec:
      containers:
      - name: frontend
        image: redbuild-frontend
        ports:
        - containerPort: 80


